#!/bin/env python3

# imports
import os
import boto3
import requests
## from decouple import config
from pycognito.aws_srp import AWSSRP
from requests_aws4auth import AWS4Auth


# parameters
harveyuser = os.environ['HARVEYUSER']
harveypass = os.environ['HARVEYPASS']



## all hard coded values taken from watching traffic generated by the mobile app.  It's also
## in the Android APK if you want to disassemble it and extract the strings.




# Authenticate ... this gives AccessToken, RefreshToken, etc
client = boto3.client('cognito-idp', 'eu-west-1')
aws = AWSSRP(username=harveyuser, password=harveypass, pool_id='eu-west-1_gtX9aUXzh', client_id='67c9dtgnbjid8l9dh5juih2iq4', client=client)
tokens = aws.authenticate_user()

# debug - print them
#tokens['AuthenticationResult']['IdToken']}

# Get Credentials ... this gives us AccessKey, SecretKeyId, etc
cog = boto3.client('cognito-identity', 'eu-west-1')
identityid = 'eu-west-1:30070db9-1478-46b4-ae5a-7d38053cd66c'
r = cog.get_credentials_for_identity( IdentityId = identityid, Logins={"cognito-idp.eu-west-1.amazonaws.com/eu-west-1_gtX9aUXzh":tokens['AuthenticationResult']['IdToken']} )

# debug - print them
###  r['Credentials']['AccessKeyId']


# Use the AWS4Auth to sign our request, and python requests to call the API
auth = AWS4Auth( r['Credentials']['AccessKeyId'], r['Credentials']['SecretKey'], 'eu-west-1', 'execute-api', session_token=r['Credentials']['SessionToken'] )
response = requests.get('https://y7xyrocicl.execute-api.eu-west-1.amazonaws.com/prod/v1/softeners/all', auth=auth)


# print it
print (response.text)

